name: Docker Image Sync

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/docker-image-sync.yml
  schedule:
    - cron: 0 15 */3 * *

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push qinglong to Dockerhub
        uses: docker/build-push-action@master
        with:
          context: docker/qinglong
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: summary/qinglong:latest

      - name: Push portainer-ce to Dockerhub
        uses: docker/build-push-action@master
        with:
          context: docker/portainer-ce
          platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: summary/portainer-ce:latest

      - name: Delete older Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         retain_days: 7
         keep_minimum_runs: 0
