name: Build Docker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push qinglong to Dockerhub
        uses: docker/build-push-action@master
        with:
          context: qinglong
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: summary/qinglong:latest

      - name: Push helloworld to Dockerhub
        uses: docker/build-push-action@master
        with:
          context: helloworld
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: summary/jd:helloworld

      - name: Push portainer-ce to Dockerhub
        uses: docker/build-push-action@master
        with:
          context: portainer-ce
          platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: summary/portainer-ce:latest

      - name: Delete older Workflows
        uses: GitRML/delete-workflow-runs@main
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         keep_minimum_runs: 0
         retain_days: 1
